# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rangelSo.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(973, 624)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(600, 10, 361, 481))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(9, 159, 341, 161))
        self.frame_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 271, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget_6 = QtGui.QTabWidget(self.frame_2)
        self.tabWidget_6.setGeometry(QtCore.QRect(0, 20, 341, 151))
        self.tabWidget_6.setStyleSheet(_fromUtf8(""))
        self.tabWidget_6.setObjectName(_fromUtf8("tabWidget_6"))
        self.adminMemoriaFisica = QtGui.QWidget()
        self.adminMemoriaFisica.setStyleSheet(_fromUtf8(""))
        self.adminMemoriaFisica.setObjectName(_fromUtf8("adminMemoriaFisica"))
        self.scrollArea_3 = QtGui.QScrollArea(self.adminMemoriaFisica)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, -10, 351, 111))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 331, 107))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.listWidgetMarcos = QtGui.QListWidget(self.scrollAreaWidgetContents_3)
        self.listWidgetMarcos.setGeometry(QtCore.QRect(10, 10, 321, 101))
        self.listWidgetMarcos.setStyleSheet(_fromUtf8("background-color: rgb(101, 255, 19);"))
        self.listWidgetMarcos.setObjectName(_fromUtf8("listWidgetMarcos"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget_6.addTab(self.adminMemoriaFisica, _fromUtf8(""))
        self.adminSwap = QtGui.QWidget()
        self.adminSwap.setStyleSheet(_fromUtf8(""))
        self.adminSwap.setObjectName(_fromUtf8("adminSwap"))
        self.scrollArea_4 = QtGui.QScrollArea(self.adminSwap)
        self.scrollArea_4.setGeometry(QtCore.QRect(0, -1, 351, 101))
        self.scrollArea_4.setStyleSheet(_fromUtf8(""))
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 331, 97))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.listWidgetPaginas = QtGui.QListWidget(self.scrollAreaWidgetContents_4)
        self.listWidgetPaginas.setGeometry(QtCore.QRect(0, 0, 321, 101))
        self.listWidgetPaginas.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 0);"))
        self.listWidgetPaginas.setObjectName(_fromUtf8("listWidgetPaginas"))
        self.listWidgetPaginas.raise_()
        self.listWidgetPaginas.raise_()
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget_6.addTab(self.adminSwap, _fromUtf8(""))
        self.frame_Planificador = QtGui.QFrame(self.frame)
        self.frame_Planificador.setGeometry(QtCore.QRect(9, -1, 341, 151))
        self.frame_Planificador.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 255);"))
        self.frame_Planificador.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Planificador.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Planificador.setObjectName(_fromUtf8("frame_Planificador"))
        self.label_Planificador = QtGui.QLabel(self.frame_Planificador)
        self.label_Planificador.setGeometry(QtCore.QRect(0, 0, 271, 17))
        self.label_Planificador.setObjectName(_fromUtf8("label_Planificador"))
        self.tabWidget_Planificador = QtGui.QTabWidget(self.frame_Planificador)
        self.tabWidget_Planificador.setGeometry(QtCore.QRect(0, 20, 341, 131))
        self.tabWidget_Planificador.setObjectName(_fromUtf8("tabWidget_Planificador"))
        self.Part1 = QtGui.QWidget()
        self.Part1.setObjectName(_fromUtf8("Part1"))
        self.tablePart1 = QtGui.QTableWidget(self.Part1)
        self.tablePart1.setEnabled(True)
        self.tablePart1.setGeometry(QtCore.QRect(0, 0, 341, 101))
        self.tablePart1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tablePart1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablePart1.setDragDropOverwriteMode(True)
        self.tablePart1.setAlternatingRowColors(False)
        self.tablePart1.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablePart1.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tablePart1.setShowGrid(True)
        self.tablePart1.setWordWrap(True)
        self.tablePart1.setCornerButtonEnabled(False)
        self.tablePart1.setObjectName(_fromUtf8("tablePart1"))
        self.tablePart1.setColumnCount(5)
        self.tablePart1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tablePart1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePart1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablePart1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablePart1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablePart1.setHorizontalHeaderItem(4, item)
        self.tabWidget_Planificador.addTab(self.Part1, _fromUtf8(""))
        self.Part2 = QtGui.QWidget()
        self.Part2.setObjectName(_fromUtf8("Part2"))
        self.edo_cores = QtGui.QTableWidget(self.Part2)
        self.edo_cores.setEnabled(True)
        self.edo_cores.setGeometry(QtCore.QRect(0, 0, 341, 101))
        self.edo_cores.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edo_cores.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.edo_cores.setDragDropOverwriteMode(True)
        self.edo_cores.setAlternatingRowColors(False)
        self.edo_cores.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.edo_cores.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.edo_cores.setShowGrid(True)
        self.edo_cores.setWordWrap(True)
        self.edo_cores.setCornerButtonEnabled(False)
        self.edo_cores.setObjectName(_fromUtf8("edo_cores"))
        self.edo_cores.setColumnCount(3)
        self.edo_cores.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.edo_cores.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.edo_cores.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.edo_cores.setHorizontalHeaderItem(2, item)
        self.tabWidget_Planificador.addTab(self.Part2, _fromUtf8(""))
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(9, 329, 341, 151))
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 271, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.checkBox = QtGui.QCheckBox(self.frame_4)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(80, 110, 171, 22))
        self.checkBox.setCheckable(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.stackedWidget = QtGui.QStackedWidget(self.frame_4)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 321, 81))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.notificaciones = QtGui.QLabel(self.page)
        self.notificaciones.setGeometry(QtCore.QRect(0, 20, 311, 61))
        self.notificaciones.setText(_fromUtf8(""))
        self.notificaciones.setScaledContents(True)
        self.notificaciones.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.notificaciones.setWordWrap(True)
        self.notificaciones.setOpenExternalLinks(False)
        self.notificaciones.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.notificaciones.setObjectName(_fromUtf8("notificaciones"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 500, 961, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.probar1 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.probar1.setObjectName(_fromUtf8("probar1"))
        self.horizontalLayout.addWidget(self.probar1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(9, 9, 591, 481))
        self.mdiArea.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuControl_Hardware = QtGui.QMenu(self.menubar)
        self.menuControl_Hardware.setObjectName(_fromUtf8("menuControl_Hardware"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNavegador = QtGui.QAction(MainWindow)
        self.actionNavegador.setObjectName(_fromUtf8("actionNavegador"))
        self.actionControl_Hardware = QtGui.QAction(MainWindow)
        self.actionControl_Hardware.setObjectName(_fromUtf8("actionControl_Hardware"))
        self.actionShell = QtGui.QAction(MainWindow)
        self.actionShell.setObjectName(_fromUtf8("actionShell"))
        self.actionValidadorTarjetas = QtGui.QAction(MainWindow)
        self.actionValidadorTarjetas.setObjectName(_fromUtf8("actionValidadorTarjetas"))
        self.menuControl_Hardware.addAction(self.actionNavegador)
        self.menuControl_Hardware.addAction(self.actionControl_Hardware)
        self.menuControl_Hardware.addAction(self.actionShell)
        self.menuControl_Hardware.addAction(self.actionValidadorTarjetas)
        self.menubar.addAction(self.menuControl_Hardware.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_Planificador.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Administrador de Memoria", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.adminMemoriaFisica), _translate("MainWindow", "Memoria Fisica           ", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.adminSwap), _translate("MainWindow", "Swap            ", None))
        self.label_Planificador.setText(_translate("MainWindow", "Planificador de procesos", None))
        self.tabWidget_Planificador.setToolTip(_translate("MainWindow", "<html><head/><body><p>sdfsd</p></body></html>", None))
        self.Part1.setToolTip(_translate("MainWindow", "<html><head/><body><p>sdasdas</p></body></html>", None))
        self.tablePart1.setSortingEnabled(False)
        item = self.tablePart1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "pid", None))
        item = self.tablePart1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom Proceso", None))
        item = self.tablePart1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tiempo", None))
        item = self.tablePart1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Núcleo", None))
        item = self.tablePart1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Estado", None))
        self.tabWidget_Planificador.setTabText(self.tabWidget_Planificador.indexOf(self.Part1), _translate("MainWindow", "Procesos", None))
        self.edo_cores.setSortingEnabled(False)
        item = self.edo_cores.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Temperatura", None))
        item = self.edo_cores.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Carga", None))
        item = self.edo_cores.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Num. Procesos", None))
        self.tabWidget_Planificador.setTabText(self.tabWidget_Planificador.indexOf(self.Part2), _translate("MainWindow", "Nucleos", None))
        self.label_3.setText(_translate("MainWindow", "Notificaciones", None))
        self.checkBox.setText(_translate("MainWindow", "Hardware Detectado", None))
        self.probar1.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.menuControl_Hardware.setTitle(_translate("MainWindow", "init", None))
        self.actionNavegador.setText(_translate("MainWindow", "Navegador", None))
        self.actionControl_Hardware.setText(_translate("MainWindow", "Control Hardware", None))
        self.actionShell.setText(_translate("MainWindow", "Shell", None))
        self.actionValidadorTarjetas.setText(_translate("MainWindow", "ValidadorTarjetas", None))

